
title: statistically ambiguous 
# email: myname@domain.com
description: > # this means to ignore newlines until "baseurl:"
   Blog of Maximilian Christ about Data Science, Statistics, Programming and everything else
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://maximilianchrist.com" # the base hostname & protocol for your site
twitter_username: MaxBenChrist
github_username:  MaxBenChrist
linkedin_username: Maximlian Christ
linkedin_url: https://www.linkedin.com/in/maximilian-christ-a6b377109?trk=hp-identity-photo

# Build settings
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-gist